/*
 * Plants mircro service
 * Micro service to order plants
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.justynafraczek.plantsshop.gateway.models;

import java.util.Objects;

import org.justynafraczek.plantsshop.types.OrderItem;
import org.justynafraczek.plantsshop.types.PlantsOrder;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * OrderRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-06T15:55:18.061200+01:00[Europe/Warsaw]")
@JsonIgnoreProperties(ignoreUnknown = true)
public class OrderRequest {

  @JsonProperty("items")
  private List<OrderItem> items = new ArrayList<>();


  @Override
  public int hashCode() {
    return Objects.hash(items);
  }

  public List<OrderItem> getItems() {
    return items;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderRequest {\n");

    sb.append("    items: ").append("\n");
    for (OrderItem item : items) {
      sb.append("        ").append(item).append("\n");
    }
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
